### ISSUE TITLE
estimated time of code release?

### ISSUE THREAD

**Issue by mikebilly** [murphylmf/M-LRM#1]
thanks for your project!, what would be the estimated date of release?

**Comment by murphylmf** [comment]
Thank you for your attention! We are currently cleaning up our code for releasing. We'll release our code as soon as the cleaning is done.

**Comment by hritam-98** [comment]
waiting for the same

**Comment by lulongfei-luffy** [comment]
waiting for the same

**Comment by HuayuanSong** [comment]
Also waiting in anticipation! Are you planning to release some models/checkpoints or a HuggingFace demo? (:

**Comment by murphylmf** [comment]
Thank you for your patience! The code is now released.
